on:
  workflow_dispatch:
  push:
    branches:
      - main

name: fox32 Unstable - Windows

jobs:
  fox32-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check out fox32core
        uses: actions/checkout@v2
        with:
          repository: fox32-arch/fox32core
          path: ./fox32core

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu

      - name: Install libgtk-3-dev, libasound2-dev, and mingw-w64
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libasound2-dev mingw-w64

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: fox32.exe
          path: target/release/fox32.exe
