on:
  workflow_dispatch:
  push:
    branches:
      - main

name: fox32 Unstable - Linux

jobs:
  fox32-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download latest fox32rom artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: fox32-arch/fox32rom
          workflow: fox32rom-unstable.yml
          workflow_conclusion: success

      - name: Move fox32.rom into the src folder
        run: cp fox32.rom/fox32.rom src/fox32.rom

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install libgtk-3-dev and libasound2-dev
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libasound2-dev

      - name: Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: fox32
          path: target/release/fox32
